version: "3.7"
services:
  app:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
    - ./workstation:/var/www
    networks:
    - default
  mysqldb:
    image: mysql:5.7.22
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - ./docker/db/mysql:/var/lib/mysql
    networks:
    - default
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
    - 8000:80
    volumes:
    - ./workstation:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/logs:/var/log/nginx
    networks:
    - default


networks:
  default:
    driver: bridge