version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
    - 8000:80
    volumes:
    - ./:/var/www
    - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/logs:/var/log/nginx
    depends_on:
    - app
    networks:
    - default
  app:
    build:
      context: Docker/php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./WorkStation:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    networks:
    - default

  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    env_file:
    - ".env"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - ./Docker/mysql:/var/lib/mysql
    ports:
    - "8989:3306"
    networks:
    - default



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
    - "8080:80"
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=${MYSQL_HOST}
    restart: unless-stopped
    depends_on:
    - mysqldb

networks:
  default:
    driver: bridge