version: '3'
services:
  web:
    image: nginx:alpine
    container_name: app
    volumes:
    - "./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    - "./Workstation:/var/www/html"
    - "./Docker/nginx/logs:/var/log/nginx"
#    - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
#    - "./etc/ssl:/etc/ssl"
    ports:
    - "8000:80"
#    - "3000:443"
    environment:
    - NGINX_HOST=${NGINX_HOST}
#    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
    - php
    - mysqldb
    networks:
    - default
  php:
    build:
      context: Docker/php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: always
    volumes:
    - "./Docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
    - "./Workstation:/var/www/html"
    networks:
    - default
#  composer:
#    image: "composer"
#    volumes:
#    - "./Workstation/app:/app"
#    command: install
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    ports:
#    - "8080:80"
#    environment:
#    - PMA_ARBITRARY=1
#    - PMA_HOST=${MYSQL_HOST}
#    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#    - MYSQL_USER=${MYSQL_USERNAME}
#    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    restart: always
#    depends_on:
#    - mysqldb
#    networks:
#    - default
  mysqldb:
    image: mysql:5.7
    ports:
    - 3306:3306
    depends_on:
    - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default
networks:
  default:
    driver: bridge